### ISSUE TITLE
Incorrect minimum python version

### ISSUE THREAD

**Issue by zedzhen** [sashaferrum/aiogram_sqlite_storage#1]
in pyproject.toml
`requires-python = ">=3.8"`
but in aiogram_sqlite_storage/sqlitestore.py python 3.10 features are used
1) union types
2) match-case

**Comment by sashaferrum** [comment]
Removed constructions from python 3.10

**Comment by zedzhen** [comment]
please upload the new version on pypi

**Comment by sashaferrum** [comment]
> please upload the new version on pypi

ok. it's ready.
